name: Node.js Package

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn build
      - name: Deploy
        id: truefipreview
        uses: ethworks/hostlify-publish@v3.3
        with:
          files: ./example
          server-url: truefipreview.io
          owner: EthWorks
          repo: hostlify
          access-token: ${{ secrets.GITHUB_TOKEN }}
