name: Node.js Package

on:
  pull_request:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn
      - run: yarn build
      - run: yarn lint
      - name: Deploy
        id: truefipreview
        uses: ethworks/hostlify-publish@v3.48
        with:
          files: ./example
          server-url: truefipreview.io
          access-token: ${{ secrets.GITHUB_TOKEN }}
